name: Academic_Research_Support_Agent
type: research
version: 1.0.0
model:
  provider: openai
  name: gpt-4
  temperature: 0.7

research_context:
  topic: 基于静态图的恶意软件分类方法研究
  current_status:
    - Initial Phase
  specific_topics:
    - General Academic Support
    - Literature Review
    - Research Planning
  research_fields:
    - Computer Science
    - Data Science
    - Machine Learning

publication_goals:
  target_journal: 北大中文核心
  acceptance_deadline: 2025-03-01
  submission_timeline: 3个月内

research_methods:
  - Literature Review
  - Data Analysis
  - Experimental Design

analysis_tools:
  - Statistical Analysis
  - Machine Learning
  - Data Visualization

resources:
  time_investment: 3 months
  computing_resources:
    - CPU: High Performance
    - GPU: Required for ML
  database_access:
    - Academic Databases
    - Research Repositories 